import { Country } from '../index'

export const COUNTRIES = [
    new Country("Afghanistan", "AF", "AFG", "Asia", "Southern Asia"),
    new Country("Aland Islands", "AX", "ALA", "Europe", "Northern Europe"),
    new Country("Albania", "AL", "ALB", "Europe", "Southern Europe"),
    new Country("Algeria", "DZ", "DZA", "Africa", "Northern Africa"),
    new Country("American Samoa", "AS", "ASM", "Oceania", "Polynesia"),
    new Country("Andorra", "AD", "AND", "Europe", "Southern Europe"),
    new Country("Angola", "AO", "AGO", "Africa", "Sub-Saharan Africa"),
    new Country("Anguilla", "AI", "AIA", "Americas", "Latin America and the Caribbean"),
    new Country("Antarctica", "AQ", "ATA", "nan", "nan"),
    new Country("Antigua and Barbuda", "AG", "ATG", "Americas", "Latin America and the Caribbean"),
    new Country("Argentina", "AR", "ARG", "Americas", "Latin America and the Caribbean"),
    new Country("Armenia", "AM", "ARM", "Asia", "Western Asia"),
    new Country("Aruba", "AW", "ABW", "Americas", "Latin America and the Caribbean"),
    new Country("Australia", "AU", "AUS", "Oceania", "Australia and New Zealand"),
    new Country("Austria", "AT", "AUT", "Europe", "Western Europe"),
    new Country("Azerbaijan", "AZ", "AZE", "Asia", "Western Asia"),
    new Country("Bahamas", "BS", "BHS", "Americas", "Latin America and the Caribbean"),
    new Country("Bahrain", "BH", "BHR", "Asia", "Western Asia"),
    new Country("Bangladesh", "BD", "BGD", "Asia", "Southern Asia"),
    new Country("Barbados", "BB", "BRB", "Americas", "Latin America and the Caribbean"),
    new Country("Belarus", "BY", "BLR", "Europe", "Eastern Europe"),
    new Country("Belgium", "BE", "BEL", "Europe", "Western Europe"),
    new Country("Belize", "BZ", "BLZ", "Americas", "Latin America and the Caribbean"),
    new Country("Benin", "BJ", "BEN", "Africa", "Sub-Saharan Africa"),
    new Country("Bermuda", "BM", "BMU", "Americas", "Northern America"),
    new Country("Bhutan", "BT", "BTN", "Asia", "Southern Asia"),
    new Country("Bolivia (Plurinational State of)", "BO", "BOL", "Americas", "Latin America and the Caribbean"),
    new Country("Bonaire, Sint Eustatius and Saba", "BQ", "BES", "Americas", "Latin America and the Caribbean"),
    new Country("Bosnia and Herzegovina", "BA", "BIH", "Europe", "Southern Europe"),
    new Country("Botswana", "BW", "BWA", "Africa", "Sub-Saharan Africa"),
    new Country("Bouvet Island", "BV", "BVT", "Americas", "Latin America and the Caribbean"),
    new Country("Brazil", "BR", "BRA", "Americas", "Latin America and the Caribbean"),
    new Country("British Indian Ocean Territory", "IO", "IOT", "Africa", "Sub-Saharan Africa"),
    new Country("Brunei Darussalam", "BN", "BRN", "Asia", "South-eastern Asia"),
    new Country("Bulgaria", "BG", "BGR", "Europe", "Eastern Europe"),
    new Country("Burkina Faso", "BF", "BFA", "Africa", "Sub-Saharan Africa"),
    new Country("Burundi", "BI", "BDI", "Africa", "Sub-Saharan Africa"),
    new Country("Cabo Verde", "CV", "CPV", "Africa", "Sub-Saharan Africa"),
    new Country("Cambodia", "KH", "KHM", "Asia", "South-eastern Asia"),
    new Country("Cameroon", "CM", "CMR", "Africa", "Sub-Saharan Africa"),
    new Country("Canada", "CA", "CAN", "Americas", "Northern America"),
    new Country("Cayman Islands", "KY", "CYM", "Americas", "Latin America and the Caribbean"),
    new Country("Central African Republic", "CF", "CAF", "Africa", "Sub-Saharan Africa"),
    new Country("Chad", "TD", "TCD", "Africa", "Sub-Saharan Africa"),
    new Country("Chile", "CL", "CHL", "Americas", "Latin America and the Caribbean"),
    new Country("China", "CN", "CHN", "Asia", "Eastern Asia"),
    new Country("Christmas Island", "CX", "CXR", "Oceania", "Australia and New Zealand"),
    new Country("Cocos (Keeling) Islands", "CC", "CCK", "Oceania", "Australia and New Zealand"),
    new Country("Colombia", "CO", "COL", "Americas", "Latin America and the Caribbean"),
    new Country("Comoros", "KM", "COM", "Africa", "Sub-Saharan Africa"),
    new Country("Congo", "CG", "COG", "Africa", "Sub-Saharan Africa"),
    new Country("Congo, Democratic Republic of the", "CD", "COD", "Africa", "Sub-Saharan Africa"),
    new Country("Cook Islands", "CK", "COK", "Oceania", "Polynesia"),
    new Country("Costa Rica", "CR", "CRI", "Americas", "Latin America and the Caribbean"),
    new Country("C�te d'Ivoire", "CI", "CIV", "Africa", "Sub-Saharan Africa"),
    new Country("Croatia", "HR", "HRV", "Europe", "Southern Europe"),
    new Country("Cuba", "CU", "CUB", "Americas", "Latin America and the Caribbean"),
    new Country("Cura�ao", "CW", "CUW", "Americas", "Latin America and the Caribbean"),
    new Country("Cyprus", "CY", "CYP", "Asia", "Western Asia"),
    new Country("Czechia", "CZ", "CZE", "Europe", "Eastern Europe"),
    new Country("Denmark", "DK", "DNK", "Europe", "Northern Europe"),
    new Country("Djibouti", "DJ", "DJI", "Africa", "Sub-Saharan Africa"),
    new Country("Dominica", "DM", "DMA", "Americas", "Latin America and the Caribbean"),
    new Country("Dominican Republic", "DO", "DOM", "Americas", "Latin America and the Caribbean"),
    new Country("Ecuador", "EC", "ECU", "Americas", "Latin America and the Caribbean"),
    new Country("Egypt", "EG", "EGY", "Africa", "Northern Africa"),
    new Country("El Salvador", "SV", "SLV", "Americas", "Latin America and the Caribbean"),
    new Country("Equatorial Guinea", "GQ", "GNQ", "Africa", "Sub-Saharan Africa"),
    new Country("Eritrea", "ER", "ERI", "Africa", "Sub-Saharan Africa"),
    new Country("Estonia", "EE", "EST", "Europe", "Northern Europe"),
    new Country("Eswatini", "SZ", "SWZ", "Africa", "Sub-Saharan Africa"),
    new Country("Ethiopia", "ET", "ETH", "Africa", "Sub-Saharan Africa"),
    new Country("Falkland Islands (Malvinas)", "FK", "FLK", "Americas", "Latin America and the Caribbean"),
    new Country("Faroe Islands", "FO", "FRO", "Europe", "Northern Europe"),
    new Country("Fiji", "FJ", "FJI", "Oceania", "Melanesia"),
    new Country("Finland", "FI", "FIN", "Europe", "Northern Europe"),
    new Country("France", "FR", "FRA", "Europe", "Western Europe"),
    new Country("French Guiana", "GF", "GUF", "Americas", "Latin America and the Caribbean"),
    new Country("French Polynesia", "PF", "PYF", "Oceania", "Polynesia"),
    new Country("French Southern Territories", "TF", "ATF", "Africa", "Sub-Saharan Africa"),
    new Country("Gabon", "GA", "GAB", "Africa", "Sub-Saharan Africa"),
    new Country("Gambia", "GM", "GMB", "Africa", "Sub-Saharan Africa"),
    new Country("Georgia", "GE", "GEO", "Asia", "Western Asia"),
    new Country("Germany", "DE", "DEU", "Europe", "Western Europe"),
    new Country("Ghana", "GH", "GHA", "Africa", "Sub-Saharan Africa"),
    new Country("Gibraltar", "GI", "GIB", "Europe", "Southern Europe"),
    new Country("Greece", "GR", "GRC", "Europe", "Southern Europe"),
    new Country("Greenland", "GL", "GRL", "Americas", "Northern America"),
    new Country("Grenada", "GD", "GRD", "Americas", "Latin America and the Caribbean"),
    new Country("Guadeloupe", "GP", "GLP", "Americas", "Latin America and the Caribbean"),
    new Country("Guam", "GU", "GUM", "Oceania", "Micronesia"),
    new Country("Guatemala", "GT", "GTM", "Americas", "Latin America and the Caribbean"),
    new Country("Guernsey", "GG", "GGY", "Europe", "Northern Europe"),
    new Country("Guinea", "GN", "GIN", "Africa", "Sub-Saharan Africa"),
    new Country("Guinea-Bissau", "GW", "GNB", "Africa", "Sub-Saharan Africa"),
    new Country("Guyana", "GY", "GUY", "Americas", "Latin America and the Caribbean"),
    new Country("Haiti", "HT", "HTI", "Americas", "Latin America and the Caribbean"),
    new Country("Heard Island and McDonald Islands", "HM", "HMD", "Oceania", "Australia and New Zealand"),
    new Country("Holy See", "VA", "VAT", "Europe", "Southern Europe"),
    new Country("Honduras", "HN", "HND", "Americas", "Latin America and the Caribbean"),
    new Country("Hong Kong", "HK", "HKG", "Asia", "Eastern Asia"),
    new Country("Hungary", "HU", "HUN", "Europe", "Eastern Europe"),
    new Country("Iceland", "IS", "ISL", "Europe", "Northern Europe"),
    new Country("India", "IN", "IND", "Asia", "Southern Asia"),
    new Country("Indonesia", "ID", "IDN", "Asia", "South-eastern Asia"),
    new Country("Iran (Islamic Republic of)", "IR", "IRN", "Asia", "Southern Asia"),
    new Country("Iraq", "IQ", "IRQ", "Asia", "Western Asia"),
    new Country("Ireland", "IE", "IRL", "Europe", "Northern Europe"),
    new Country("Isle of Man", "IM", "IMN", "Europe", "Northern Europe"),
    new Country("Israel", "IL", "ISR", "Asia", "Western Asia"),
    new Country("Italy", "IT", "ITA", "Europe", "Southern Europe"),
    new Country("Jamaica", "JM", "JAM", "Americas", "Latin America and the Caribbean"),
    new Country("Japan", "JP", "JPN", "Asia", "Eastern Asia"),
    new Country("Jersey", "JE", "JEY", "Europe", "Northern Europe"),
    new Country("Jordan", "JO", "JOR", "Asia", "Western Asia"),
    new Country("Kazakhstan", "KZ", "KAZ", "Asia", "Central Asia"),
    new Country("Kenya", "KE", "KEN", "Africa", "Sub-Saharan Africa"),
    new Country("Kiribati", "KI", "KIR", "Oceania", "Micronesia"),
    new Country("Korea (Democratic People's Republic of)", "KP", "PRK", "Asia", "Eastern Asia"),
    new Country("Korea, Republic of", "KR", "KOR", "Asia", "Eastern Asia"),
    new Country("Kuwait", "KW", "KWT", "Asia", "Western Asia"),
    new Country("Kyrgyzstan", "KG", "KGZ", "Asia", "Central Asia"),
    new Country("Lao People's Democratic Republic", "LA", "LAO", "Asia", "South-eastern Asia"),
    new Country("Latvia", "LV", "LVA", "Europe", "Northern Europe"),
    new Country("Lebanon", "LB", "LBN", "Asia", "Western Asia"),
    new Country("Lesotho", "LS", "LSO", "Africa", "Sub-Saharan Africa"),
    new Country("Liberia", "LR", "LBR", "Africa", "Sub-Saharan Africa"),
    new Country("Libya", "LY", "LBY", "Africa", "Northern Africa"),
    new Country("Liechtenstein", "LI", "LIE", "Europe", "Western Europe"),
    new Country("Lithuania", "LT", "LTU", "Europe", "Northern Europe"),
    new Country("Luxembourg", "LU", "LUX", "Europe", "Western Europe"),
    new Country("Macao", "MO", "MAC", "Asia", "Eastern Asia"),
    new Country("Madagascar", "MG", "MDG", "Africa", "Sub-Saharan Africa"),
    new Country("Malawi", "MW", "MWI", "Africa", "Sub-Saharan Africa"),
    new Country("Malaysia", "MY", "MYS", "Asia", "South-eastern Asia"),
    new Country("Maldives", "MV", "MDV", "Asia", "Southern Asia"),
    new Country("Mali", "ML", "MLI", "Africa", "Sub-Saharan Africa"),
    new Country("Malta", "MT", "MLT", "Europe", "Southern Europe"),
    new Country("Marshall Islands", "MH", "MHL", "Oceania", "Micronesia"),
    new Country("Martinique", "MQ", "MTQ", "Americas", "Latin America and the Caribbean"),
    new Country("Mauritania", "MR", "MRT", "Africa", "Sub-Saharan Africa"),
    new Country("Mauritius", "MU", "MUS", "Africa", "Sub-Saharan Africa"),
    new Country("Mayotte", "YT", "MYT", "Africa", "Sub-Saharan Africa"),
    new Country("Mexico", "MX", "MEX", "Americas", "Latin America and the Caribbean"),
    new Country("Micronesia (Federated States of)", "FM", "FSM", "Oceania", "Micronesia"),
    new Country("Moldova, Republic of", "MD", "MDA", "Europe", "Eastern Europe"),
    new Country("Monaco", "MC", "MCO", "Europe", "Western Europe"),
    new Country("Mongolia", "MN", "MNG", "Asia", "Eastern Asia"),
    new Country("Montenegro", "ME", "MNE", "Europe", "Southern Europe"),
    new Country("Montserrat", "MS", "MSR", "Americas", "Latin America and the Caribbean"),
    new Country("Morocco", "MA", "MAR", "Africa", "Northern Africa"),
    new Country("Mozambique", "MZ", "MOZ", "Africa", "Sub-Saharan Africa"),
    new Country("Myanmar", "MM", "MMR", "Asia", "South-eastern Asia"),
    new Country("Namibia", "nan", "NAM", "Africa", "Sub-Saharan Africa"),
    new Country("Nauru", "NR", "NRU", "Oceania", "Micronesia"),
    new Country("Nepal", "NP", "NPL", "Asia", "Southern Asia"),
    new Country("Netherlands", "NL", "NLD", "Europe", "Western Europe"),
    new Country("New Caledonia", "NC", "NCL", "Oceania", "Melanesia"),
    new Country("New Zealand", "NZ", "NZL", "Oceania", "Australia and New Zealand"),
    new Country("Nicaragua", "NI", "NIC", "Americas", "Latin America and the Caribbean"),
    new Country("Niger", "NE", "NER", "Africa", "Sub-Saharan Africa"),
    new Country("Nigeria", "NG", "NGA", "Africa", "Sub-Saharan Africa"),
    new Country("Niue", "NU", "NIU", "Oceania", "Polynesia"),
    new Country("Norfolk Island", "NF", "NFK", "Oceania", "Australia and New Zealand"),
    new Country("North Macedonia", "MK", "MKD", "Europe", "Southern Europe"),
    new Country("Northern Mariana Islands", "MP", "MNP", "Oceania", "Micronesia"),
    new Country("Norway", "NO", "NOR", "Europe", "Northern Europe"),
    new Country("Oman", "OM", "OMN", "Asia", "Western Asia"),
    new Country("Pakistan", "PK", "PAK", "Asia", "Southern Asia"),
    new Country("Palau", "PW", "PLW", "Oceania", "Micronesia"),
    new Country("Palestine, State of", "PS", "PSE", "Asia", "Western Asia"),
    new Country("Panama", "PA", "PAN", "Americas", "Latin America and the Caribbean"),
    new Country("Papua New Guinea", "PG", "PNG", "Oceania", "Melanesia"),
    new Country("Paraguay", "PY", "PRY", "Americas", "Latin America and the Caribbean"),
    new Country("Peru", "PE", "PER", "Americas", "Latin America and the Caribbean"),
    new Country("Philippines", "PH", "PHL", "Asia", "South-eastern Asia"),
    new Country("Pitcairn", "PN", "PCN", "Oceania", "Polynesia"),
    new Country("Poland", "PL", "POL", "Europe", "Eastern Europe"),
    new Country("Portugal", "PT", "PRT", "Europe", "Southern Europe"),
    new Country("Puerto Rico", "PR", "PRI", "Americas", "Latin America and the Caribbean"),
    new Country("Qatar", "QA", "QAT", "Asia", "Western Asia"),
    new Country("R�union", "RE", "REU", "Africa", "Sub-Saharan Africa"),
    new Country("Romania", "RO", "ROU", "Europe", "Eastern Europe"),
    new Country("Russian Federation", "RU", "RUS", "Europe", "Eastern Europe"),
    new Country("Rwanda", "RW", "RWA", "Africa", "Sub-Saharan Africa"),
    new Country("Saint Barth�lemy", "BL", "BLM", "Americas", "Latin America and the Caribbean"),
    new Country("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", "Africa", "Sub-Saharan Africa"),
    new Country("Saint Kitts and Nevis", "KN", "KNA", "Americas", "Latin America and the Caribbean"),
    new Country("Saint Lucia", "LC", "LCA", "Americas", "Latin America and the Caribbean"),
    new Country("Saint Martin (French part)", "MF", "MAF", "Americas", "Latin America and the Caribbean"),
    new Country("Saint Pierre and Miquelon", "PM", "SPM", "Americas", "Northern America"),
    new Country("Saint Vincent and the Grenadines", "VC", "VCT", "Americas", "Latin America and the Caribbean"),
    new Country("Samoa", "WS", "WSM", "Oceania", "Polynesia"),
    new Country("San Marino", "SM", "SMR", "Europe", "Southern Europe"),
    new Country("Sao Tome and Principe", "ST", "STP", "Africa", "Sub-Saharan Africa"),
    new Country("Saudi Arabia", "SA", "SAU", "Asia", "Western Asia"),
    new Country("Senegal", "SN", "SEN", "Africa", "Sub-Saharan Africa"),
    new Country("Serbia", "RS", "SRB", "Europe", "Southern Europe"),
    new Country("Seychelles", "SC", "SYC", "Africa", "Sub-Saharan Africa"),
    new Country("Sierra Leone", "SL", "SLE", "Africa", "Sub-Saharan Africa"),
    new Country("Singapore", "SG", "SGP", "Asia", "South-eastern Asia"),
    new Country("Sint Maarten (Dutch part)", "SX", "SXM", "Americas", "Latin America and the Caribbean"),
    new Country("Slovakia", "SK", "SVK", "Europe", "Eastern Europe"),
    new Country("Slovenia", "SI", "SVN", "Europe", "Southern Europe"),
    new Country("Solomon Islands", "SB", "SLB", "Oceania", "Melanesia"),
    new Country("Somalia", "SO", "SOM", "Africa", "Sub-Saharan Africa"),
    new Country("South Africa", "ZA", "ZAF", "Africa", "Sub-Saharan Africa"),
    new Country("South Georgia and the South Sandwich Islands", "GS", "SGS", "Americas", "Latin America and the Caribbean"),
    new Country("South Sudan", "SS", "SSD", "Africa", "Sub-Saharan Africa"),
    new Country("Spain", "ES", "ESP", "Europe", "Southern Europe"),
    new Country("Sri Lanka", "LK", "LKA", "Asia", "Southern Asia"),
    new Country("Sudan", "SD", "SDN", "Africa", "Northern Africa"),
    new Country("Suriname", "SR", "SUR", "Americas", "Latin America and the Caribbean"),
    new Country("Svalbard and Jan Mayen", "SJ", "SJM", "Europe", "Northern Europe"),
    new Country("Sweden", "SE", "SWE", "Europe", "Northern Europe"),
    new Country("Switzerland", "CH", "CHE", "Europe", "Western Europe"),
    new Country("Syrian Arab Republic", "SY", "SYR", "Asia", "Western Asia"),
    new Country("Taiwan, Province of China", "TW", "TWN", "Asia", "Eastern Asia"),
    new Country("Tajikistan", "TJ", "TJK", "Asia", "Central Asia"),
    new Country("Tanzania, United Republic of", "TZ", "TZA", "Africa", "Sub-Saharan Africa"),
    new Country("Thailand", "TH", "THA", "Asia", "South-eastern Asia"),
    new Country("Timor-Leste", "TL", "TLS", "Asia", "South-eastern Asia"),
    new Country("Togo", "TG", "TGO", "Africa", "Sub-Saharan Africa"),
    new Country("Tokelau", "TK", "TKL", "Oceania", "Polynesia"),
    new Country("Tonga", "TO", "TON", "Oceania", "Polynesia"),
    new Country("Trinidad and Tobago", "TT", "TTO", "Americas", "Latin America and the Caribbean"),
    new Country("Tunisia", "TN", "TUN", "Africa", "Northern Africa"),
    new Country("Turkey", "TR", "TUR", "Asia", "Western Asia"),
    new Country("Turkmenistan", "TM", "TKM", "Asia", "Central Asia"),
    new Country("Turks and Caicos Islands", "TC", "TCA", "Americas", "Latin America and the Caribbean"),
    new Country("Tuvalu", "TV", "TUV", "Oceania", "Polynesia"),
    new Country("Uganda", "UG", "UGA", "Africa", "Sub-Saharan Africa"),
    new Country("Ukraine", "UA", "UKR", "Europe", "Eastern Europe"),
    new Country("United Arab Emirates", "AE", "ARE", "Asia", "Western Asia"),
    new Country("United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", "Europe", "Northern Europe"),
    new Country("United States of America", "US", "USA", "Americas", "Northern America"),
    new Country("United States Minor Outlying Islands", "UM", "UMI", "Oceania", "Micronesia"),
    new Country("Uruguay", "UY", "URY", "Americas", "Latin America and the Caribbean"),
    new Country("Uzbekistan", "UZ", "UZB", "Asia", "Central Asia"),
    new Country("Vanuatu", "VU", "VUT", "Oceania", "Melanesia"),
    new Country("Venezuela (Bolivarian Republic of)", "VE", "VEN", "Americas", "Latin America and the Caribbean"),
    new Country("Viet Nam", "VN", "VNM", "Asia", "South-eastern Asia"),
    new Country("Virgin Islands (British)", "VG", "VGB", "Americas", "Latin America and the Caribbean"),
    new Country("Virgin Islands (U.S.)", "VI", "VIR", "Americas", "Latin America and the Caribbean"),
    new Country("Wallis and Futuna", "WF", "WLF", "Oceania", "Polynesia"),
    new Country("Western Sahara", "EH", "ESH", "Africa", "Northern Africa"),
    new Country("Yemen", "YE", "YEM", "Asia", "Western Asia"),
    new Country("Zambia", "ZM", "ZMB", "Africa", "Sub-Saharan Africa"),
    new Country("Zimbabwe", "ZW", "ZWE", "Africa", "Sub-Saharan Africa"),
]